import React from "react";
import "./globals.css";
import { Comfortaa } from "next/font/google";
import { Footer, Navbar } from "@/components/Common";

const comfortaa = Comfortaa({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => (
  <html lang="en">
    <body className={comfortaa.className}>
      <Navbar />
      <div className="pb-20">{children}</div>
      <Footer />
    </body>
  </html>
);

export default RootLayout;
